# Generated by Django 4.0.5 on 2022-06-24 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=128)),
                ('from_social', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
